### ISSUE TITLE
导入工程报错

### ISSUE THREAD

**Issue by chingHao** [jokermonn/GankOr#1]
下载你的项目导入studio  
Error:(46, 13) Failed to resolve: com.google.code.gson:gson:2.7
<a href="openFile:/Users/ChingHao/GankOr/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:(37, 20) Failed to resolve: com.squareup.leakcanary:leakcanary-android-no-op:1.3.1
<a href="openFile:/Users/ChingHao/GankOr/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:(39, 18) Failed to resolve: com.squareup.leakcanary:leakcanary-android:1.4-beta1
<a href="openFile:/Users/ChingHao/GankOr/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by jokermonn** [comment]
第一个是 gson 的，第二三个是内存泄漏检测。第一个你可以在 gradle 里面删了重新 sync 一下，第二三个可以删了
